### ISSUE TITLE
Text foreground color sticks on black

### ISSUE THREAD

**Issue by srogers** [Downright-Development/Cucumberbeans#16]
The text foreground color is black, which makes it invisible in my theme. I can change it in preferences, but it reverts back to black again every time Netbeans is restarted. "Inherited" is probably a more universal choice.

![Screenshot_2_27_13_1_07_AM](https://f.cloud.github.com/assets/8566/199915/6b10ceb8-80ac-11e2-9030-51f8532059ed.png)

**Comment by Downright-Development** [comment]
Team,

This is still an issue within netbeans 8.2 and will be the first issue tackled!
