### ISSUE TITLE
IllegalStateException when editing feature files

### ISSUE THREAD

**Issue by sworisbreathing** [Downright-Development/Cucumberbeans#23]
[original NetBeans issue](https://netbeans.org/bugzilla/show_bug.cgi?id=225734)

Looks like GherkinSyntaxErrorHighlightingTask is havening some issues parsing feature files.

**Comment by Chris2011** [comment]
I think the lexer needs some fixes.

**Comment by Downright-Development** [comment]
@Chris2011 Has this been fixed? If not, please open a new issue. I'm attempting to cleanup all these old issues. I know you mentioned something about the lexer needing to be looked at.

**Comment by Chris2011** [comment]
No, i don't think so. The Lexer or token File needs a fix.
