### ISSUE TITLE
Status of development and bug fixing -- comments welcome

### ISSUE THREAD

**Issue by dzsessona** [Downright-Development/Cucumberbeans#25]
From an email of Andras:

Q: I hope you are well and I apologize to disturb you with my email. I would like to ask whether is there any chance you are going to continue developing the Cetriolo plugin? I started to use it because I'm a test engineer and I want to test my project using BDD method. On the other hand, I don't want to use Eclipse. If so, than I would be happy and as a user-tester I would like to contribute to your project.

A: First of all thank you for your feedback and sorry for the late response. Basically this was project was something i wrote because i needed to use. I put it in github because i thought it could be valuable for other people too. And that was the case. The problems with this project though is that there are few bugs and a few feature missing, expecially regarding multiple gherkin language support. So to be completely honest with you I really have no time to work on it by myself. I think this plugin is a good starting point to make the support of cucumber awesome in Netbeans but unless someone starts to contribute to the project i will not keep developing it. In the next month i might review it a little bit to get rid of the bugs that are currently open and make some documentation, but as I told you I am not going to keep developing it by myself. If i do, it will be for supporting the scalatest framework too, but as yoiu can imagine that would be a big undertaking.

**Comment by Downright-Development** [comment]
(U) Development has begun! Closing this as it's unnecessary.
