### ISSUE TITLE
Please provide an example to how to create a test solution

### ISSUE THREAD

**Issue by Chris2011** [Downright-Development/Cucumberbeans#30]
I used SpecFlow for a .NET project. It is really nice implemented into VS.

Now I use netbeans and I tried this plugin. For now I really don't know how to create tests with this plugin. Normally, do new file -> unit tests -> create unit test for existing class.
After this I can do a lot of stuff, can select the package/class to create a unit testfile for an existing class. Now I selected the unit test packages to create a feature file insode of this, only to separate tests and code. I wrote some stuff inside and I don't know how to create a step definition file from within this feature file. Is this possible? When yes, how? Atm it says to me, that there is no implementation  found for this step.

I would really like to use BDD with netbeans, but for me some features are missing in this plugin.

For me I would like to have a little tutorial from the beginning. Creat a class with your logic (return hello world), create a feature file after this create a step file. Run test. This would be very helpfull.

Is the feature missing to create a step definition file, from within the feature file, I will create a new bug for this.

Thx for the work and kind regards

Chris

**Comment by Downright-Development** [comment]
Chris,

I’ve seen you’ve forked this repository and began work! First off, that’s super awesome!

A great deal of time has passed, do you still need assistance grasping Cucumber? I’d be glad to help!

Best,
Downright Dev.

**Comment by Chris2011** [comment]
Hey @Downright-Development,

thx for your info. Yes I worked on it but atm, I stopped because oif other priorities. But I'm willing to work on it again, if you have time and can help me. There are some stuff that I want to accomplish.

- Fix the Lexer/Parser - There is an exception, when you start to delete the last lines one by one until you get to the string.

- Rename the project - I've chosen Cucumberbeans, it is more meaningful and everyone knows it, than Cetriolo (Which means cucumber in italy).

- Fix the scanning of the steps and annotation files : #31 but for this, I have to know, why he did this. For which reason.

It would be great if you can help here out.


Cheers

Chris

**Comment by Chris2011** [comment]
Here is the discussion about the exception: https://github.com/Chris2011/Cucumberbeans/pull/2

**Comment by Downright-Development** [comment]
@chris2011

Looking at your fork, I’d like to use that as the base copy, with a few additional changes of mine to merge in afterwards. I’ll work on simply cloning your fork and replacing the repo’s content with yours later today (3am here, woke up for a drink) :) 

Have a great night.

Best,
Downright (sleepy) Dev!

**Comment by Chris2011** [comment]
@Downright-Development great to hear. That would be nice to bring a stable Cucumber repo to NetBeans again. Will commit some things later. Here it is 9am, now I'm at work, Join our NetBeans slack chan to talk together :)

**Comment by Chris2011** [comment]
So my master is up to date. Feel free to clone it and merge it into here or should I provide a PR?

**Comment by Downright-Development** [comment]
Chris, if you provide a PR that sure as heck make my life easier! I’ll get to it after work today.

Thanks!

Best,
Downright Dev

**Comment by Chris2011** [comment]
Ok, will do it later or tomorrow. Thx :)
