### ISSUE TITLE
Searching for Cucumber steps.. Task cannot be killed and locks files

### ISSUE THREAD

**Issue by dkirrane** [Downright-Development/Cucumberbeans#31]
The 'Searching for Cucumber steps...' cannot be killed and seems to run forever.
It also prevents me from cleaning my Maven project cause it seems to lock feature files under the target directory.

![image](https://cloud.githubusercontent.com/assets/1280116/9580401/2787a33a-4ff1-11e5-9fba-b109327d7686.png)

```
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: Updates available to version NetBeans 8.0.2 Patch 2
Java: 1.7.0_79; Java HotSpot(TM) 64-Bit Server VM 24.79-b02
Runtime: Java(TM) SE Runtime Environment 1.7.0_79-b15
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)
User directory: C:\Users\#####\AppData\Roaming\NetBeans\8.0.2
Cache directory: C:\Users\#####\AppData\Local\NetBeans\Cache\8.0.2
```

**Comment by dzsessona** [comment]
I stopped working on this plugin since I stopped working on cucumber, unfortunately because there are no other commmiters on this project, I stopped mantaining it.

**Comment by Chris2011** [comment]
It would be great to fix this bug I have the same issue and it prevents me from using it. I would like to have a look into it, can you explain why is it needed to scan for Cucumber annotations? What is is used fore?

**Comment by Chris2011** [comment]
It starts searching after opening a project and un-/set a project to a main project. I can fix this, via preventing the search but I want to know, why it is needed to scan all the time for steps or annotations. Please explain it @dzsessona

**Comment by Downright-Development** [comment]
@Chris2011 If this is still an issue post your merge, please re-open a new ticket. I'm attempting to clean up all old issues.

**Comment by Downright-Development** [comment]
@Chris2011

Perhaps a better understanding of a feature file would guide you to why this was implemented.

A feature file is setup with the structure of...

Feature: required field, name of your feature here
  0-Many “Scenarios” (similar to @test in JUnit)

There’s additional blocks such as scenario-outlines and backgrounds, but for now I’ll only explain a simple scenario.

You can think of ONE scenario equalling ONE test. Hence the @test reference. Scenarios are NOT to leak between themselves, instead be isolated tests that can run without any additional prerequisites. 

Typically we try to follow the “Given, When, Then” pattern.

Given - setup your world
And - additional given steps
And - more given steps
When - an action happens that you’re testing
Then - assert the results from the “when” are correct

As you can see, this BDD pattern allows one scenario to setup the environment it neeeds for one singular test.

Now to answer your question,

The “given, when, then” bits are called “Steps”. A step In A feature file is almost a “proxy” to the code. “Step definitions” are the concrete implementations of steps from your feature file :).

The need to scan for step implementations was for a feature on the plugin. One of the abilities this plugin allows is that you may Alt+Enter, or click the tooltip, on the feature file’s step, and it will automatically pull up the step definition. (Similar to how you can control click a method in netbeans, and it’ll open the method).

A problem you may have experienced is that the project your step definition was in, was not opened in netbeans. 

I’ve used this plugin in netbeans 8.2 at work, and I’ve not experienced the issue the ticket is stating, though we use ANT as our build tool.

**Comment by Chris2011** [comment]
Ok great, thx for explanation. So maybe the scan needs only scanning the project not every open project. Then I think the logic needs a change.

**Comment by Downright-Development** [comment]
@chris2011 no, it will definitely need to scan every open project as step definitions can exist within multiple projects.

If you can repeat this bug on Netbeans 8.2 and a fresh install of the plugin, please give step by step instructions how. (How you ran it, etc.) I’ve not been able to repeat this.

**Comment by Chris2011** [comment]
Ok, I understand. but there is no progress seeing when the IDE does it for JUnit or TestNG tests. I think, it is not needed to see it, that the Plugin does this(?). IMHO. If it is fast enough and will not block any other stuff.

**Comment by Chris2011** [comment]
@Downright-Development did you say, that you can't reproduce the bug?

**Comment by Downright-Development** [comment]
@chris2011 yes, I cannot reproduce this issue. Which is why I initially closed it.  If you can reproduce this, please post a new detailed issue:)

**Comment by Chris2011** [comment]
OK, let ne Check, Maybe i removed the Scan.

**Comment by Chris2011** [comment]
@Downright-Development yes, I think it came from my code changes: https://github.com/Downright-Development/Cucumberbeans/commit/13a5a072db6d7d6cf89a489bcd08d528dc2f17f1#diff-ebd9f35bac54063faf5327c0f80c766d

there is a lot of stuff, happend there but I think i commented some stuff out. So maybe someone with more knowledge about the scanning the files, can have a look here, please and fix it or rechange it. I try it too.
