### ISSUE TITLE
TravisCI occasionally fails on a specific maven dependency which causes the automated build to timeout 

### ISSUE THREAD

**Issue by Downright-Development** [Downright-Development/Cucumberbeans#40]

**Comment by Chris2011** [comment]
Does this happen sometimes? Because the build is now green.

**Comment by Downright-Development** [comment]
@chris2011, yes I noticed it happened yesterday ... I have configured the build to kick off every 24Hr if there’s been no pull requests, and it got stuck on a maven repo. Tried it again, and it passed successfully

**Comment by Downright-Development** [comment]
Fixed. Updated the travisCI yml.
